name: Publish Package

on:
  release:
    types: [created]

permissions:
  actions: write
  contents: write
  deployments: write

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          set-safe-directory: false



      - name: Install app dependencies
        run: yarn install --frozen-lockfile

      - name: Build Svelte app
        run: yarn build

      - name: Update Package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file:  dist/${{ github.event.repository.name }}/package.json
          field: version
          value: ${{ github.event.release.tag_name }}

      - name:  Release Artifact - Web
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
              dist



  deploy_github:
    name: Deploy to github
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Dowload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Update Package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file:  dist/${{ github.event.repository.name }}/package.json
          field: name
          value: "@${{github.actor}}/${{ github.event.repository.name }}"

      - name: Setup Node.js - Github Registry
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish Package in github
        run: |
          cd dist/${{ github.event.repository.name }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy_npmjs:
    name: Deploy to npmjs
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Dowload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Setup Node.js - Npm Registry
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name:  Publish Package in npmjs
        run: |
          cd dist/${{ github.event.repository.name }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
